name = "telegram-auto-message2"
main = "src/bible-flex-router.js"
compatibility_date = "2025-01-01"

[vars]
ADMIN_CHAT_ID = "-1003860270266"
ADMIN_THREAD_ID = "220"
CONTROL_CHAT_IDS = "-1003745214852,-1003697946094"
TARGET_CHAT_ID = "-1001861714695"

[observability]
enabled = true
