name: Telegram Auto Message

on:
  schedule:
    - cron: "0 17,20 * * *"
  workflow_dispatch:

jobs:
  send-message:
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram message
        run: |
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.BOT_TOKEN }}/sendMessage" \
          -d "chat_id=${{ secrets.CHAT_ID }}" \
          -d "text=Браћо, подсетник: прочитајте правила групе и држите разговор нормалним."
